[tool.pytest.ini_options]
console_output_style = "progress"
log_auto_indent = true
minversion = 6.0

[tool.coverage.run]
cover_pylib = false
branch = true
include = [
	"Nyr/*",
	"Nyr.Test/*",
]
omit = [
	"Nyr/__main__.py",
]

[tool.coverage.report]
show_missing = true
skip_covered = true
precision = 3
include = [
	"Nyr/*",
	"Nyr.Test/*",
]
omit = [
	"Nyr/__main__.py",
]

[tool.coverage.html]
directory = "reports/coverage/htmlreport"
skip_covered = false

[tool.coverage.xml]
output = "reports/coverage/coverage.xml"
